### ISSUE TITLE
peer icmp reply not handled

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-linkmgrd#153]
As per the title, there had been seen that there is no `handleRecv` called for peer icmp reply packets.

**Comment by lolyu** [comment]
For `PF_PACKET`, if the recv buffer length is less than the packet size, only recv buffer size is copied into the buffer, and the rest of the packet is dropped:
https://github.com/torvalds/linux/blob/f2b220ef93ea34ff6ce48fec382689cf02099f39/net/packet/af_packet.c#L3439-L3468

**Comment by zjswhhh** [comment]
After enable more debugging log and handler tracking, I found the following facts in a 20-interval window with a repro:
* The number of attempts to read into buffer == the number of packet parsing handlers was invoked 
* The invoked handlers executed successfully: it either read nothing, or valid peer replies, or valid self replies. 
* Sequence number of the parsed packets are continuous, non-interrupted, but the handlers were **delayed** for over 40ms hence caused the timeout and heartbeat "missing" event. 
* We parsed only 35 out of 40 in the time window. 

Hence it seems to be a performance issue instead of a real packet drop. Checked the time of repro, didn't see CPU/memory usage spikes on the device. 

After searching around the asio user community, I found same issue happened for other people too, and it led to a performance issue of asio `strands`: https://sourceforge.net/p/asio/mailman/message/35693245/

Proposed solution: incrementing `ASIO_STRAND_IMPLEMENTATIONS` to 1024.  
Did an experiment, the issue didn't repro for over 20 hours.
